---

- name: set address
  command: "SMCIPMITool {{ item.0 }} {{ ipmi_user }} {{ ipmi_password }} microblade switch lan ip A1 {{ item.1 }}"
  with_together:
    - "{{ cmm_current_list }}"
    - "{{ switch_list }}"

- name: set netmask
  command: "SMCIPMITool {{ item }} {{ ipmi_user }} {{ ipmi_password }} microblade switch lan mask A1 {{ netmask }}"
  with_items:
    - "{{ cmm_current_list }}"

- name: set gateway
  command: "SMCIPMITool {{ item }} {{ ipmi_user }} {{ ipmi_password }} microblade switch lan gateway A1 {{ gateway }}"
  with_items:
    - "{{ cmm_current_list }}"

- name: wait 10 seconds
  pause:
    seconds: 10